#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Apr 09, 2021 07:55:22 AM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import main_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    main_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1920x1017+106+38")
        top.minsize(136, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.005, rely=0.0, relheight=0.259
                , relwidth=0.198)
        self.Labelframe1.configure(relief='raised')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(relief="raised")
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.105, rely=0.042, height=44, width=77
                , bordermode='ignore')
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=main_support.createRFID)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''RFID''')

        self.Button2 = tk.Button(self.Labelframe1)
        self.Button2.place(relx=0.105, rely=0.259, height=44, width=77
                , bordermode='ignore')
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=main_support.createLinehorizontal)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''LINE''')

        self.Button3 = tk.Button(self.Labelframe1)
        self.Button3.place(relx=0.105, rely=0.475, height=44, width=77
                , bordermode='ignore')
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=main_support.createLinevertical)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''LINE''')

        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.421, rely=0.346, height=10, width=48
                , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#000000")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")

        self.Label3 = tk.Label(self.Labelframe1)
        self.Label3.place(relx=0.471, rely=0.475, height=49, width=10
                , bordermode='ignore')
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#000000")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Label''')

        self.Labelframe2 = tk.LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.421, rely=0.042, relheight=0.24
                , relwidth=0.134, bordermode='ignore')
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(background="#0000a0")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")

        self.Button13 = tk.Button(self.Labelframe1)
        self.Button13.place(relx=0.105, rely=0.738, height=44, width=77
                , bordermode='ignore')
        self.Button13.configure(activebackground="#ececec")
        self.Button13.configure(activeforeground="#000000")
        self.Button13.configure(background="#d9d9d9")
        self.Button13.configure(command=main_support.crossroadLine)
        self.Button13.configure(disabledforeground="#a3a3a3")
        self.Button13.configure(foreground="#000000")
        self.Button13.configure(highlightbackground="#d9d9d9")
        self.Button13.configure(highlightcolor="black")
        self.Button13.configure(pady="0")
        self.Button13.configure(text='''CROSSROAD''')

        self.Label13 = tk.Label(self.Labelframe1)
        self.Label13.place(relx=0.426, rely=0.825, height=10, width=47
                , bordermode='ignore')
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(background="#000000")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(highlightbackground="#d9d9d9")
        self.Label13.configure(highlightcolor="black")

        self.Label17 = tk.Label(self.Labelframe1)
        self.Label17.place(relx=0.476, rely=0.753, height=49, width=9
                , bordermode='ignore')
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(activeforeground="black")
        self.Label17.configure(background="#000000")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(foreground="#000000")
        self.Label17.configure(highlightbackground="#d9d9d9")
        self.Label17.configure(highlightcolor="black")
        self.Label17.configure(text='''Label''')

        self.mapFrame = tk.Canvas(top)
        self.mapFrame.place(relx=0.219, rely=0.01, relheight=0.972
                , relwidth=0.788)
        self.mapFrame.configure(background="#d9d9d9")
        self.mapFrame.configure(borderwidth="2")
        self.mapFrame.configure(highlightbackground="#d9d9d9")
        self.mapFrame.configure(highlightcolor="black")
        self.mapFrame.configure(insertbackground="black")
        self.mapFrame.configure(relief="ridge")
        self.mapFrame.configure(selectbackground="blue")
        self.mapFrame.configure(selectforeground="white")

        self.Labelframe3 = tk.LabelFrame(top)
        self.Labelframe3.place(relx=0.005, rely=0.256, relheight=0.214
                , relwidth=0.202)
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''PROPERTY_LINE''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")

        self.lenlineEntry = tk.Entry(self.Labelframe3)
        self.lenlineEntry.place(relx=0.207, rely=0.188, height=27, relwidth=0.191
                , bordermode='ignore')
        self.lenlineEntry.configure(background="white")
        self.lenlineEntry.configure(disabledforeground="#a3a3a3")
        self.lenlineEntry.configure(font="TkFixedFont")
        self.lenlineEntry.configure(foreground="#000000")
        self.lenlineEntry.configure(highlightbackground="#d9d9d9")
        self.lenlineEntry.configure(highlightcolor="black")
        self.lenlineEntry.configure(insertbackground="black")
        self.lenlineEntry.configure(selectbackground="blue")
        self.lenlineEntry.configure(selectforeground="white")

        self.functionEntry = ttk.Combobox(self.Labelframe3)
        self.functionEntry.place(relx=0.204, rely=0.344, relheight=0.096
                , relwidth=0.194, bordermode='ignore')
        self.value_list = ['None','Line','Hook','Position',]
        self.functionEntry.configure(values=self.value_list)
        self.functionEntry.configure(exportselection="0")
        self.functionEntry.configure(state='readonly')
        self.functionEntry.configure(takefocus="")

        self.Label4 = tk.Label(self.Labelframe3)
        self.Label4.place(relx=0.008, rely=0.734, height=20, width=65
                , bordermode='ignore')
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Rotate type''')

        self.Label5 = tk.Label(self.Labelframe3)
        self.Label5.place(relx=0.026, rely=0.188, height=16, width=45
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Len''')

        self.Label7 = tk.Label(self.Labelframe3)
        self.Label7.place(relx=0.545, rely=0.179, height=15, width=65
                , bordermode='ignore')
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Degree rote''')

        self.Label10 = tk.Label(self.Labelframe3)
        self.Label10.place(relx=0.543, rely=0.358, height=14, width=65
                , bordermode='ignore')
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Speed max''')

        self.Label11 = tk.Label(self.Labelframe3)
        self.Label11.place(relx=0.537, rely=0.587, height=17, width=55
                , bordermode='ignore')
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''Wait time''')

        self.Label12 = tk.Label(self.Labelframe3)
        self.Label12.place(relx=0.008, rely=0.358, height=14, width=65
                , bordermode='ignore')
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''Fucntion''')

        self.rotatetypeEntry = ttk.Combobox(self.Labelframe3)
        self.rotatetypeEntry.place(relx=0.207, rely=0.734, relheight=0.096
                , relwidth=0.191, bordermode='ignore')
        self.value_list = ['None','Center','Side',]
        self.rotatetypeEntry.configure(values=self.value_list)
        self.rotatetypeEntry.configure(state='readonly')
        self.rotatetypeEntry.configure(takefocus="")

        self.speedmaxEntry = ttk.Combobox(self.Labelframe3)
        self.speedmaxEntry.place(relx=0.775, rely=0.358, relheight=0.096
                , relwidth=0.168, bordermode='ignore')
        self.value_list = ['Slow','Normal','High',]
        self.speedmaxEntry.configure(values=self.value_list)
        self.speedmaxEntry.configure(state='readonly')
        self.speedmaxEntry.configure(takefocus="")

        self.waittimeEntry = tk.Entry(self.Labelframe3)
        self.waittimeEntry.place(relx=0.775, rely=0.569, height=27
                , relwidth=0.165, bordermode='ignore')
        self.waittimeEntry.configure(background="white")
        self.waittimeEntry.configure(disabledforeground="#a3a3a3")
        self.waittimeEntry.configure(font="TkFixedFont")
        self.waittimeEntry.configure(foreground="#000000")
        self.waittimeEntry.configure(highlightbackground="#d9d9d9")
        self.waittimeEntry.configure(highlightcolor="black")
        self.waittimeEntry.configure(insertbackground="black")
        self.waittimeEntry.configure(selectbackground="blue")
        self.waittimeEntry.configure(selectforeground="white")

        self.degreeroteEntry = tk.Entry(self.Labelframe3)
        self.degreeroteEntry.place(relx=0.775, rely=0.161, height=27
                , relwidth=0.165, bordermode='ignore')
        self.degreeroteEntry.configure(background="white")
        self.degreeroteEntry.configure(disabledforeground="#a3a3a3")
        self.degreeroteEntry.configure(font="TkFixedFont")
        self.degreeroteEntry.configure(foreground="#000000")
        self.degreeroteEntry.configure(highlightbackground="#d9d9d9")
        self.degreeroteEntry.configure(highlightcolor="black")
        self.degreeroteEntry.configure(insertbackground="black")
        self.degreeroteEntry.configure(selectbackground="blue")
        self.degreeroteEntry.configure(selectforeground="white")

        self.Label18 = tk.Label(self.Labelframe3)
        self.Label18.place(relx=0.026, rely=0.55, height=21, width=64
                , bordermode='ignore')
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(activeforeground="black")
        self.Label18.configure(background="#d9d9d9")
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(foreground="#000000")
        self.Label18.configure(highlightbackground="#d9d9d9")
        self.Label18.configure(highlightcolor="black")
        self.Label18.configure(text='''Line type''')

        self.linetypeEntry = ttk.Combobox(self.Labelframe3)
        self.linetypeEntry.place(relx=0.207, rely=0.55, relheight=0.096
                , relwidth=0.186, bordermode='ignore')
        self.value_list = ['One','Cross','Fork',]
        self.linetypeEntry.configure(values=self.value_list)
        self.linetypeEntry.configure(takefocus="")

        self.Labelframe5 = tk.LabelFrame(top)
        self.Labelframe5.place(relx=0.005, rely=0.472, relheight=0.101
                , relwidth=0.203)
        self.Labelframe5.configure(relief='groove')
        self.Labelframe5.configure(foreground="black")
        self.Labelframe5.configure(text='''RFID''')
        self.Labelframe5.configure(background="#d9d9d9")
        self.Labelframe5.configure(highlightbackground="#d9d9d9")
        self.Labelframe5.configure(highlightcolor="black")

        self.Label6 = tk.Label(self.Labelframe5)
        self.Label6.place(relx=0.051, rely=0.583, height=21, width=87
                , bordermode='ignore')
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Name''')

        self.nameRFIDEntry = tk.Entry(self.Labelframe5)
        self.nameRFIDEntry.place(relx=0.308, rely=0.583, height=27
                , relwidth=0.242, bordermode='ignore')
        self.nameRFIDEntry.configure(background="white")
        self.nameRFIDEntry.configure(disabledforeground="#a3a3a3")
        self.nameRFIDEntry.configure(font="TkFixedFont")
        self.nameRFIDEntry.configure(foreground="#000000")
        self.nameRFIDEntry.configure(highlightbackground="#d9d9d9")
        self.nameRFIDEntry.configure(highlightcolor="black")
        self.nameRFIDEntry.configure(insertbackground="black")
        self.nameRFIDEntry.configure(selectbackground="blue")
        self.nameRFIDEntry.configure(selectforeground="white")

        self.Label14 = tk.Label(self.Labelframe5)
        self.Label14.place(relx=0.039, rely=0.223, height=21, width=76
                , bordermode='ignore')
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''Index''')

        self.indexCardEntry = tk.Entry(self.Labelframe5)
        self.indexCardEntry.place(relx=0.308, rely=0.194, height=27
                , relwidth=0.242, bordermode='ignore')
        self.indexCardEntry.configure(background="white")
        self.indexCardEntry.configure(disabledforeground="#a3a3a3")
        self.indexCardEntry.configure(font="TkFixedFont")
        self.indexCardEntry.configure(foreground="#000000")
        self.indexCardEntry.configure(highlightbackground="#d9d9d9")
        self.indexCardEntry.configure(highlightcolor="black")
        self.indexCardEntry.configure(insertbackground="black")
        self.indexCardEntry.configure(selectbackground="blue")
        self.indexCardEntry.configure(selectforeground="white")

        self.lab48 = tk.LabelFrame(top)
        self.lab48.place(relx=0.004, rely=0.58, relheight=0.198, relwidth=0.203)
        self.lab48.configure(relief='groove')
        self.lab48.configure(foreground="black")
        self.lab48.configure(text='''Labelframe''')
        self.lab48.configure(background="#d9d9d9")
        self.lab48.configure(highlightbackground="#d9d9d9")
        self.lab48.configure(highlightcolor="black")

        self.Label15 = tk.Label(self.lab48)
        self.Label15.place(relx=0.103, rely=0.269, height=29, width=55
                , bordermode='ignore')
        self.Label15.configure(activebackground="#f9f9f9")
        self.Label15.configure(activeforeground="black")
        self.Label15.configure(background="#d9d9d9")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(highlightbackground="#d9d9d9")
        self.Label15.configure(highlightcolor="black")
        self.Label15.configure(text='''Start''')

        self.Label16 = tk.Label(self.lab48)
        self.Label16.place(relx=0.103, rely=0.488, height=30, width=55
                , bordermode='ignore')
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(activeforeground="black")
        self.Label16.configure(background="#d9d9d9")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(highlightbackground="#d9d9d9")
        self.Label16.configure(highlightcolor="black")
        self.Label16.configure(text='''End''')

        self.startEntry = tk.Entry(self.lab48)
        self.startEntry.place(relx=0.257, rely=0.269, height=27, relwidth=0.162
                , bordermode='ignore')
        self.startEntry.configure(background="white")
        self.startEntry.configure(disabledforeground="#a3a3a3")
        self.startEntry.configure(font="TkFixedFont")
        self.startEntry.configure(foreground="#000000")
        self.startEntry.configure(highlightbackground="#d9d9d9")
        self.startEntry.configure(highlightcolor="black")
        self.startEntry.configure(insertbackground="black")
        self.startEntry.configure(selectbackground="blue")
        self.startEntry.configure(selectforeground="white")

        self.endEntry = tk.Entry(self.lab48)
        self.endEntry.place(relx=0.257, rely=0.488, height=27, relwidth=0.165
                , bordermode='ignore')
        self.endEntry.configure(background="white")
        self.endEntry.configure(disabledforeground="#a3a3a3")
        self.endEntry.configure(font="TkFixedFont")
        self.endEntry.configure(foreground="#000000")
        self.endEntry.configure(highlightbackground="#d9d9d9")
        self.endEntry.configure(highlightcolor="black")
        self.endEntry.configure(insertbackground="black")
        self.endEntry.configure(selectbackground="blue")
        self.endEntry.configure(selectforeground="white")

        self.Button5 = tk.Button(self.lab48)
        self.Button5.place(relx=0.463, rely=0.697, height=34, width=57
                , bordermode='ignore')
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(command=main_support.send)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''SEND''')

        self.Button7 = tk.Button(self.lab48)
        self.Button7.place(relx=0.103, rely=0.697, height=34, width=57
                , bordermode='ignore')
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(command=main_support.setupStep)
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''OK''')

        self.Button8 = tk.Button(self.lab48)
        self.Button8.place(relx=0.283, rely=0.697, height=34, width=57
                , bordermode='ignore')
        self.Button8.configure(activebackground="#ececec")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(command=main_support.reset)
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''RESET''')

        self.Label1 = tk.Label(self.lab48)
        self.Label1.place(relx=0.542, rely=0.269, height=18, width=34
                , bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Head''')

        self.headEntry = ttk.Combobox(self.lab48)
        self.headEntry.place(relx=0.746, rely=0.249, relheight=0.124
                , relwidth=0.213, bordermode='ignore')
        self.value_list = ['Front','Back',]
        self.headEntry.configure(values=self.value_list)
        self.headEntry.configure(takefocus="")

        self.Label9 = tk.Label(self.lab48)
        self.Label9.place(relx=0.537, rely=0.498, height=21, width=64
                , bordermode='ignore')
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Name AGV''')

        self.nameAGV = tk.Entry(self.lab48)
        self.nameAGV.place(relx=0.743, rely=0.498, height=27, relwidth=0.216
                , bordermode='ignore')
        self.nameAGV.configure(background="white")
        self.nameAGV.configure(disabledforeground="#a3a3a3")
        self.nameAGV.configure(font="TkFixedFont")
        self.nameAGV.configure(foreground="#000000")
        self.nameAGV.configure(highlightbackground="#d9d9d9")
        self.nameAGV.configure(highlightcolor="black")
        self.nameAGV.configure(insertbackground="black")
        self.nameAGV.configure(selectbackground="blue")
        self.nameAGV.configure(selectforeground="white")

        self.Labelframe4 = tk.LabelFrame(top)
        self.Labelframe4.place(relx=0.005, rely=0.895, relheight=0.088
                , relwidth=0.203)
        self.Labelframe4.configure(relief='groove')
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Labelframe''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")

        self.saveButton = tk.Button(self.Labelframe4)
        self.saveButton.place(relx=0.103, rely=0.389, height=34, width=95
                , bordermode='ignore')
        self.saveButton.configure(activebackground="#ececec")
        self.saveButton.configure(activeforeground="#000000")
        self.saveButton.configure(background="#d9d9d9")
        self.saveButton.configure(command=main_support.saveDesign)
        self.saveButton.configure(disabledforeground="#a3a3a3")
        self.saveButton.configure(foreground="#000000")
        self.saveButton.configure(highlightbackground="#d9d9d9")
        self.saveButton.configure(highlightcolor="black")
        self.saveButton.configure(pady="0")
        self.saveButton.configure(text='''Save''')

        self.loadButton = tk.Button(self.Labelframe4)
        self.loadButton.place(relx=0.486, rely=0.344, height=34, width=97
                , bordermode='ignore')
        self.loadButton.configure(activebackground="#ececec")
        self.loadButton.configure(activeforeground="#000000")
        self.loadButton.configure(background="#d9d9d9")
        self.loadButton.configure(command=main_support.loadDesign)
        self.loadButton.configure(disabledforeground="#a3a3a3")
        self.loadButton.configure(foreground="#000000")
        self.loadButton.configure(highlightbackground="#d9d9d9")
        self.loadButton.configure(highlightcolor="black")
        self.loadButton.configure(pady="0")
        self.loadButton.configure(text='''Load''')

        self.Labelframe7 = tk.LabelFrame(top)
        self.Labelframe7.place(relx=0.005, rely=0.786, relheight=0.104
                , relwidth=0.203)
        self.Labelframe7.configure(relief='groove')
        self.Labelframe7.configure(foreground="black")
        self.Labelframe7.configure(text='''Control''')
        self.Labelframe7.configure(background="#d9d9d9")
        self.Labelframe7.configure(highlightbackground="#d9d9d9")
        self.Labelframe7.configure(highlightcolor="black")

        self.Button4 = tk.Button(self.Labelframe7)
        self.Button4.place(relx=0.075, rely=0.557, height=34, width=55
                , bordermode='ignore')
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(command=main_support.startAGV)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Start''')

        self.Button6 = tk.Button(self.Labelframe7)
        self.Button6.place(relx=0.275, rely=0.557, height=34, width=55
                , bordermode='ignore')
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(command=main_support.stopAGV)
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Stop''')

        self.Label8 = tk.Label(self.Labelframe7)
        self.Label8.place(relx=0.082, rely=0.189, height=21, width=61
                , bordermode='ignore')
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Name AGV''')

        self.nameAgvEntry = tk.Entry(self.Labelframe7)
        self.nameAgvEntry.place(relx=0.27, rely=0.189, height=27, relwidth=0.19
                , bordermode='ignore')
        self.nameAgvEntry.configure(background="white")
        self.nameAgvEntry.configure(disabledforeground="#a3a3a3")
        self.nameAgvEntry.configure(font="TkFixedFont")
        self.nameAgvEntry.configure(foreground="#000000")
        self.nameAgvEntry.configure(highlightbackground="#d9d9d9")
        self.nameAgvEntry.configure(highlightcolor="black")
        self.nameAgvEntry.configure(insertbackground="black")
        self.nameAgvEntry.configure(selectbackground="blue")
        self.nameAgvEntry.configure(selectforeground="white")

        self.Button9 = tk.Button(self.Labelframe7)
        self.Button9.place(relx=0.514, rely=0.566, height=34, width=47
                , bordermode='ignore')
        self.Button9.configure(activebackground="#ececec")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(command=main_support.checkStatus)
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(text='''Status''')

if __name__ == '__main__':
    vp_start_gui()





